# <center>Тема 2. Углубленные приемы pandas, collections, numpy</center>
## <center>Практическое задание. Работа с векторами в библиотеке NumPy</center>

In [3]:
import numpy as np
import pandas as pd

**1. Создайте numpy массив с числами от 100 с шагом в 10, размера 10х5**

In [110]:
rows_count = 10
columns_count = 5
step = 10
start = 100
arr = np.arange(start=start, stop=start + step * rows_count * columns_count, step=step)
two_dim_arr = arr.reshape(rows_count, columns_count)
print(two_dim_arr)

[[100 110 120 130 140]
 [150 160 170 180 190]
 [200 210 220 230 240]
 [250 260 270 280 290]
 [300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]
 [500 510 520 530 540]
 [550 560 570 580 590]]


**2. Создайте numpy массив с числами от 100 с шагом в 10, размера 10х5 заполеннный змейкой**  
---------->  
<---------  
---------->  

In [111]:
# не совсем понятно когда возвращается копия, а когда view
two_dim_arr[1::, 1:-1] = 0
# two_dim_arr_slice = two_dim_arr[1::2]
# two_dim_arr_slice = two_dim_arr_slice[::,::-1]
# two_dim_arr[1::2] = two_dim_arr_slice
print(two_dim_arr)

[[100 110 120 130 140]
 [150   0   0   0 190]
 [200   0   0   0 240]
 [250   0   0   0 290]
 [300   0   0   0 340]
 [350   0   0   0 390]
 [400   0   0   0 440]
 [450   0   0   0 490]
 [500   0   0   0 540]
 [550   0   0   0 590]]


**3. Вычтите из каждого ряда первого массива соответствующее значение из второго**  
Result
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [83]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
print(a_2d.shape[0])

3


In [84]:
for i in range(a_2d.shape[0]):
    a_2d[i] = a_2d[i] - b_1d[i]
print(a_2d)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


**4. Заменить все положительные числа массива на 1, отрицательные на 0**

In [80]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))
print(X)

[[-316 -441  653 ...  773  961 -475]
 [-187  456 -432 ...  168  273 -169]
 [ 936  475 -128 ...  408 -892 -310]
 ...
 [-921  396  457 ...  646 -450 -387]
 [ 645  943 -435 ...  863 -920  790]
 [ 641 -548  379 ...  347  -67 -352]]


In [81]:
X[X > 0] = 1
X[X < 0] = 0
print(X)

[[0 0 1 ... 1 1 0]
 [0 1 0 ... 1 1 0]
 [1 1 0 ... 1 0 0]
 ...
 [0 1 1 ... 1 0 0]
 [1 1 0 ... 1 0 1]
 [1 0 1 ... 1 0 0]]


**5. Создать numpy массив нулей размера NхM c границей из единиц, шириной K**

In [88]:
N = 10
M = 6
K = 2

In [118]:
arr = np.zeros((10, 6))
b = arr[:K:][:K:]
arr = b
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


**6. Вывести все name и среднее число заказов типа 2 по месяцам, для которых общая сумма заказов за месяц, в которых число заказов типа 1 больше числа заказов типа 2, превышает среднюю сумму заказов по всем месяцам.**  
Дополнительно: не использовать присваивание

In [ ]:
# не менять
np.random.seed(17)
data = pd.DataFrame({'name': np.random.randint(0, 10, size=1000),
                     'date': pd.date_range('2019-01-01', '2020-01-01', periods=1000),
                     'order_type_1': np.random.randint(0, 100, size=1000),
                     'order_type_2': np.random.randint(0, 100, size=1000)})
data.loc[data['order_type_1'] % 5 == 0, 'order_type_1'] = np.nan
data.loc[data['order_type_2'] % 3 == 0, 'order_type_2'] = np.nan
data.head()

# order_type - сумма заказа типа 1 и типа 2 на определенную дату. NaN если заказа не было

In [ ]:
# Ваш код здесь